targets:
  $default:
    builders:
      graphql_codegen:
        options:
          schema: lib/graphql/schema.graphql
          clients:
            - graphql
            - graphql_flutter
          scalars:
            DateTime:
              type: DateTime
            JSON:
              type: Map<String, dynamic>
          outputDirectory: ../generated
          generatePossibleTypes: true
          naming:
            types:
              - "Query"
              - "Mutation"